const Icons = {
  Drawer: require("@assets/icons/ic_drawer.png"),
  Logo: require("@assets/icons/AppTopLogo.png"),
  Logobak: require("@assets/icons/AppTopLogo_back.png"),
  Search: require("@assets/icons/ic_search.png"),
  Cart: require("@assets/icons/ic_cart.png"),
  Deals: require("@assets/icons/ic_deals.png"),
  Coupons: require("@assets/icons/ic_coupons.png"),
  Countdown: require("@assets/icons/ic_countdown.png"),
  Favorite: require("@assets/icons/ic_favorite.png"),
  FavoriteSelected: require("@assets/icons/ic_favorite_selected.png"),
  Share: require("@assets/icons/ic_share.png"),
  Home: require("@assets/icons/ic_home.png"),
  User: require("@assets/icons/user.png"),
  Delete: require("@assets/icons/ic_delete.png"),
  EnFlag: require("@assets/icons/english.png"),
  ZhFlag: require("@assets/icons/chinese.png"),
  Selected: require("@assets/icons/ic_selected.png"),
  Close: require("@assets/icons/ic_close.png"),
  UncheckCircle: require("@assets/icons/uncheck_circle.png"),
  CheckCircle: require("@assets/icons/check_circle.png"),
  DownArrow: require("@assets/icons/ic_down_arrow.png"),
  Address: require("@assets/icons/ic_address.png"),
  Shipping: require("@assets/icons/ic_shipping.png"),
  Star: require("@assets/icons/ic_star.png"),
  Language: require("@assets/icons/ic_language.png"),
  Feedback: require("@assets/icons/ic_feedback.png"),
  SignOut: require("@assets/icons/ic_sign_out.png"),
  Add: require("@assets/icons/ic_add.png"),
  RightIcon: require("@assets/icons/rightIcon.png"),
  Filter: require("@assets/icons/ic_filter.png"),
  SmallClose: require("@assets/icons/ic_small_close.png"),
  Sort: require("@assets/icons/ic_sort.png"),
  SliderMarker: require("@assets/icons/ic_slider_marker.png"),
  StarRating: require("@assets/icons/ic_star_rating.png"),
  StarRatingSelected: require("@assets/icons/ic_star_rating_selected.png"),
  View: require("@assets/icons/ic_view.png"),
  Payment: require("@assets/icons/ic_payment.png"),
  Cash: require("@assets/icons/ic_cash.png"),
  Paypal: require("@assets/icons/ic_paypal.png"),
  RazorPay: require("@assets/icons/ic_razorpay.png"),
  Stripe: require("@assets/icons/ic_stripe_payment.png"),
  FaceBook: require("@assets/icons/ic_face.png"),
  Checked: require("@assets/icons/ic_checked.png"),
  UnCheck: require("@assets/icons/ic_uncheck.png"),
  MenuBg: require("@assets/icons/imageBg.png"),
  BrandTitle: require("@assets/icons/brandTitle.png"),
  CategoryTitle: require("@assets/icons/categoryTitle.png"),
  Feedback: require("@assets/icons/feedback.png"),
  Comments: require("@assets/icons/comments.png"),
  Info: require("@assets/icons/info.png"),
  Notification: require("@assets/icons/notification.png"),
  // MenuBg: require("@assets/icons/imageBg1.png"),
  // MenuBg: require("@assets/icons/imageBg2.png"),
  // MenuBg: require("@assets/icons/imageBg3.png"),
  // MenuBg: require("@assets/icons/imageBg4.png"),
  // MenuBg: require("@assets/icons/imageBg5.png")
};

export default Icons;
