const Languages = {
  zh: {
    Submit: "提交",
    "Empty List": "空列表",
    "What are you looking for?": "搜索产品",
    "See All": "更多",
    "Browser By Category": "浏览类别",
    Brands: "品牌",
    "Free Shipping": "免邮",
    Quantity: "数量",
    Total: "总共",
    Checkout: "结账",
    "My Orders": "我的订单",
    "My WishList": "我的收藏",
    Yours: "你的",
    "My Address Book": "我的地址",
    "New Feeds": "新资讯",
    "Add to Cart": "加到购物车",
    Results: "结果",
    Result: "结果",
    "Change Language": "切换语言",
    "Rate App": "评价App",
    "Share App": "分享App",
    "Share": "分享",
    "Wishlist": "收藏",
    "Can not connect to server": "无法连接到服务器",
    Sponsored: "推荐产品",
    Category: "类别",
    "Price Range": "价格范围",
    "Price Sort": "价格排序",
    Brand: "品牌",
    Feedback: "反馈",
    Email: "邮件",
    Password: "密码",
    "Sign In": "登录",
    "Sign Up": "注册",
    "Do you have account with TuoTuo?": "已有账号?",
    "First Name": "名字",
    "Last Name": "姓氏",
    "Order Received": "感谢您的购买",
    Telephone: "电话",
    Street: "地址",
    City: "城市",
    Postcode: "邮政编码",
    "Choose Country": "选择国家",
    "Shipping Methods": "配送方式",
    "Please choose shipping method": "请选择配送方式.",
    "Please input all fields": "请输入所有表格",
    "Payment Methods": "支付方式",
    "Payment": "支付",
    "Sign Out": "退出",
    "Add Address": "添加地址",
    "Choose Region": "选择地区",
    Status: "状态",
    Created: "创建",
    Code: "代码",
    "Email or password is incorrect": "邮件或密码不正确.",
    "Don't have any shipping methods at your address":
      "你所选的地址不在配送范围",
    "Top Deals": "热门销售",
    "Sort by": "排序方式",
    Filter: "筛选",
    Clear: "清空",
    Apply: "响应",
    None: "无",
    Tags: "标签",
    Attributes: "属性",
    "Read more": "查看更多",
    "View": "查看详情",
    "Price": "价格",
    Availability: "可用性",
    "Out of stock": "缺货",
    "in stock": "有货",
    "Vendor Information": "供应商信息",
    Name: "名字",
    "Store name": "店铺名字",
    Email: "邮件",
    Rating: "评分",
    Specification: "规格",
    Categories: "类别",
    "Products for vendor": "供应商的产品",
    "Login With Facebook": "Login With Facebook",
    Welcome: "欢迎",
    "Remember me": "记住账号",
    "Successfully": "感谢使用Mr.TuoTuo, 您的操作已完成。",
    "Select Avatar": "选择头像",
    "Order Number": "订单号",
    "Order Details": "订单详情",
    "Coming Soon": "即将到来",
    "Reviews": "评论",
    "Support": "联系客服",
    "All": "全部",
    "My Profile": "我的信息",
    "Coupons": "我的优惠卷",
    "Coupon Code": "优惠卷代码",
    "English Only": "请使用英文填写您的目的地址",
    "Countdown": "限时抢购",
    "Back": "返回",
    "Select Variation": "选择规格",
    "Please select your options": "请选择您的选项",
    "My Comments": "我的评价",
    "Invalid Coupon Code": "无效验证码",
    "Alert": "提示",
    "Order Information": "订单详情",
    "View Product": "浏览产品",
    "Privacy Policy And Terms Of Service": "隐私与服务条款",
    "Notification Setting": "消息设置",
    "Turn on/off notification": "消息提示【开启或关闭】",
    "Subtotal": "小记",
    "Shipping": "运费",
    "Tax": "销售税",
    "Discount": "优惠",
    "Total": "总共",
    "Your Order": "我的订单",
    "Payment Methods": "付款方式",
    "Forgot Password": "修改密码",
    "Forgot your password?": "忘记密码？",
    "Recover Password": "找回密码"
  },
  en: {
    Submit: "Submit",
    "Empty List": "Empty List",
    "What are you looking for?": "What are you looking for?",
    "See All": "See All",
    "Browser By Category": "Browser By Category",
    Brands: "Brands",
    "Free Shipping": "Free Shipping",
    Quantity: "Quantity",
    Total: "Total",
    Checkout: "Checkout",
    "My Orders": "My Orders",
    "My WishList": "My WishList",
    Yours: "Yours",
    "My Address Book": "My Address Book",
    "New Feeds": "New Feeds",
    "Add to Cart": "Add to Cart",
    Results: "Results",
    Result: "Result",
    "Change Language": "Change Language",
    "Rate App": "Rate App",
    "Share App": "Share App",
    "Can not connect to server": "Can not connect to server.",
    Sponsored: "Sponsored",
    Category: "Category",
    "Price Range": "Price Range",
    Brand: "Brand",
    Feedback: "Feedback",
    Email: "Email",
    Password: "Password",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    "Do you have account with TuoTuo?": "Do you have account with TuoTuo?",
    "First Name": "First Name",
    "Last Name": "Last Name",
    "Done ! Thank you for your order.": "Done ! Thank you for your order.",
    Telephone: "Telephone",
    Street: "Street",
    City: "City",
    Postcode: "Postcode",
    "Choose Country": "Choose Country",
    "Shipping Methods": "Shipping Methods",
    "Please choose shipping method": "Please choose shipping method.",
    "Please input all fields": "Please input all fields",
    "Payment Methods": "Payment Methods",
    "Sign Out": "Sign Out",
    "Add Address": "Add Address",
    "Choose Region": "Choose Region",
    Status: "Status",
    Created: "Created",
    Code: "Code",
    "Email or password is incorrect": "Email or password is incorrect.",
    "Don't have any shipping methods at your address":
    "Don't have any shipping methods at your address",
    "Top Deals": "Top Deals",
    "Sort by": "Sort by",
    Filter: "Filter",
    Clear: "Clear",
    Apply: "Apply",
    None: "None",
    Tags: "Tags",
    Attributes: "Attributes",
    "Read more": "Read more",
    Availability: "Availability",
    "Out of stock": "Out of stock",
    "in stock": "in stock",
    "Vendor Information": "Vendor Information",
    Name: "Name",
    "Store name": "Store name",
    Email: "Email",
    Rating: "Rating",
    Specification: "Specification",
    Categories: "Categories",
    Reviews: "Reviews",
    "Products for vendor": "Products for vendor",
    "Login With Facebook": "Login With Facebook",
    Welcome: "Welcome",
    "Remember me": "Remember me",
    "Successfully": "Thank you for using Mr.TuoTuo, Your request has complete successfully.",
    "Select Avatar": "Select Avatar",
    "Order Number": "Order Number",
    "Order Details": "Order Details",
    "Coming Soon": "Coming Soon",
    "Reviews": "Reviews",
    "Support": "Support",
    "All": "All",
    "Coupons": "Coupons",
    "Coupon Code": "Coupon Code",
    "English Only": "Shipping Information in English Only.",
    "Countdown": "Countdown",
    "Share": "Share",
    "Wishlist": "Wishlist",
    "Back": "Back",
    "Select Variation": "Select Variation",
    "Please select your options": "Please select your options",
    "Invalid Coupon Code": "Invalid Coupon Code",
    "Alert": "Alert",
    "Order Received": "Order Received",
    "Order Information": "Order Information",
    "View Product": "View Product",
    "Privacy Policy And Terms Of Service": "Privacy Policy And Terms Of Service",
    "Notification Setting": "Notification Setting",
    "Turn on/off notification": "Turn On/off notification",
    "Payment": "Payment",
    "Subtotal": "Subtotal",
    "Shipping": "Shipping",
    "Tax": "Tax",
    "Discount": "Discount",
    "Total": "Total",
    "Your Order": "Your Order",
    "Payment Methods": "Payment Methods",
    "Forgot your password?": "Forgot your password?",
    "Recover Password": "Recover Password"
  }
};

export default Languages;
